// Vulnerability Library — Complete Reference Knowledge Base
// Curated educational repository mapped to all SecuraX scanner engines

export const SCANNER_TABS = [
  {
    id: 'web',
    label: 'Web Core',
    labelFull: 'Web Application Core Assessment',
    icon: '🌐',
    color: 'from-cyan-500 to-blue-500',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    textColor: 'text-cyan-400',
    desc: 'Core web vulnerabilities including authentication flaws, authorization bypasses, and business logic errors.',
  },
  {
    id: 'dast',
    label: 'DAST',
    labelFull: 'Dynamic Application Testing (ZAP / Nuclei / Nikto)',
    icon: '🔍',
    color: 'from-orange-500 to-red-500',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    textColor: 'text-orange-400',
    desc: 'Runtime application security vulnerabilities discovered via active automated scans and fuzzing.',
  },
  {
    id: 'sast',
    label: 'SAST',
    labelFull: 'Static Code Analysis (Bandit / Semgrep / Gitleaks)',
    icon: '🔬',
    color: 'from-purple-500 to-indigo-500',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
    textColor: 'text-purple-400',
    desc: 'Source code security defects, hardcoded credentials, and unsafe coding patterns identified statically.',
  },
  {
    id: 'network',
    label: 'Network',
    labelFull: 'Network & Port Reconnaissance (Nmap)',
    icon: '🌐',
    color: 'from-blue-500 to-cyan-500',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    textColor: 'text-blue-400',
    desc: 'Exposed network ports, unneeded services, and daemon fingerprinting across target hosts.',
  },
  {
    id: 'ssl',
    label: 'SSL/TLS',
    labelFull: 'Cryptographic & Transport Security (SSLyze)',
    icon: '🔒',
    color: 'from-green-500 to-emerald-500',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    textColor: 'text-green-400',
    desc: 'Flaws in SSL/TLS protocols, deprecated cipher suites, expired certificates, and TLS misconfigurations.',
  },
  {
    id: 'deps',
    label: 'Dependencies',
    labelFull: 'Supply Chain & Dependency Audit (OSV.dev)',
    icon: '📦',
    color: 'from-yellow-500 to-amber-500',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/30',
    textColor: 'text-yellow-400',
    desc: 'Known CVEs in open-source third-party dependencies, packages, and transitive libraries.',
  },
  {
    id: 'server',
    label: 'Server Internal',
    labelFull: 'Web Server Hardening & Config Audit (White-box)',
    icon: '⚙️',
    color: 'from-slate-400 to-slate-600',
    bgColor: 'bg-slate-500/10',
    borderColor: 'border-slate-500/30',
    textColor: 'text-slate-400',
    desc: 'Misconfigurations in Apache, Nginx, missing defense-in-depth headers, and exposed administrative files.',
  },
  {
    id: 'server_ext',
    label: 'Server External',
    labelFull: 'External Server Probing & Banner Audit (Black-box)',
    icon: '🖥️',
    color: 'from-purple-500 to-pink-500',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
    textColor: 'text-purple-400',
    desc: 'External probing for server banner disclosure, dangerous HTTP verbs (TRACE/OPTIONS), and known web server CVEs.',
  },
  {
    id: 'docker',
    label: 'Docker',
    labelFull: 'Container & Host Security Audit',
    icon: '🐳',
    color: 'from-sky-500 to-blue-500',
    bgColor: 'bg-sky-500/10',
    borderColor: 'border-sky-500/30',
    textColor: 'text-sky-400',
    desc: 'Privileged containers, dangerous volume mounts, container breakout vectors, and exposed daemon sockets.',
  },
  {
    id: 'dns',
    label: 'DNS / Email',
    labelFull: 'Domain & Email Authentication Security',
    icon: '📧',
    color: 'from-teal-500 to-green-500',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    textColor: 'text-teal-400',
    desc: 'Email spoofing vectors (missing SPF, DKIM, DMARC) and unauthorized DNS zone transfers (AXFR).',
  },
  {
    id: 'wordpress',
    label: 'WordPress',
    labelFull: 'WordPress CMS & Plugin Audit (WPScan)',
    icon: '🌀',
    color: 'from-blue-400 to-indigo-500',
    bgColor: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/30',
    textColor: 'text-indigo-400',
    desc: 'Outdated WordPress core installations, vulnerable plugins/themes, and exposed XML-RPC interfaces.',
  },
];

const DIFFICULTY_ORDER = { easy: 1, medium: 2, hard: 3 };

export const VULN_LIBRARY = {
  // ── Web Core ────────────────────────────────────────────────────
  web: [
    {
      id: 'open_redirect',
      label: 'Open URL Redirection',
      difficulty: 'easy',
      summary: 'A parameter takes a URL and redirects the user without verifying that the destination domain is safe. Attackers abuse this for convincing phishing campaigns or to leak OAuth authorization tokens via manipulated redirect_uri handlers.',
      remediation: 'Avoid user-controllable redirects. If essential, validate destination against a strict internal domain allowlist or map targets to predefined numerical IDs.',
      portswigger: 'https://portswigger.net/web-security/open-redirection',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/open-redirect',
      owasp: 'https://owasp.org/www-community/attacks/Open_redirect',
      youtube: [{ title: 'Open Redirects in Modern Bug Bounty', url: 'https://www.youtube.com/results?search_query=open+redirect+bug+bounty' }],
    },
    {
      id: 'parameter_pollution',
      label: 'HTTP Parameter Pollution (HPP)',
      difficulty: 'medium',
      summary: 'Injecting duplicate parameter keys (e.g. ?id=1&id=2) causes discrepancies between front-end WAFs, load balancers, and backend application servers. Can be leveraged to bypass input validation filters and alter application business logic.',
      remediation: 'Ensure web server and application frameworks adhere to consistent parameter parsing rules or reject requests with duplicate parameter keys.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/parameter-pollution',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/04-Testing_for_HTTP_Parameter_Pollution',
      youtube: [{ title: 'HTTP Parameter Pollution Explained', url: 'https://www.youtube.com/results?search_query=http+parameter+pollution' }],
    },
    {
      id: 'broken_auth_logic',
      label: 'Authentication Logic Bypass',
      difficulty: 'hard',
      summary: 'Flaws in session state management, password reset flows, or multi-factor authentication (MFA) validation. Allows an attacker to impersonate arbitrary users or bypass secondary verification steps entirely.',
      remediation: 'Implement centralized, well-tested authentication libraries, enforce atomic session state transitions, and rate-limit verification tokens.',
      portswigger: 'https://portswigger.net/web-security/authentication',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/authentication-bypass',
      owasp: 'https://owasp.org/www-project-top-ten/2017/A2_2017-Broken_Authentication',
      youtube: [{ title: 'Authentication Flaws in Web Apps', url: 'https://www.youtube.com/results?search_query=broken+authentication+bug+bounty' }],
    },
  ],

  // ── DAST ────────────────────────────────────────────────────────
  dast: [
    {
      id: 'xss',
      label: 'Cross-Site Scripting (XSS)',
      difficulty: 'easy',
      summary: 'Occurs when an application includes untrusted data in a web page without proper validation or escaping. Attackers inject malicious client-side JavaScript to hijack user sessions, steal cookies, deface websites, or redirect victims to phishing portals.',
      remediation: 'Implement contextual output encoding, adopt a strong Content Security Policy (CSP), and utilize modern frontend frameworks that auto-escape data.',
      portswigger: 'https://portswigger.net/web-security/cross-site-scripting',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/xss-cross-site-scripting',
      owasp: 'https://owasp.org/www-community/attacks/xss/',
      youtube: [{ title: 'XSS Bug Bounty Methodology — NahamSec', url: 'https://www.youtube.com/results?search_query=nahamsec+XSS+bug+bounty' }],
    },
    {
      id: 'sqli',
      label: 'SQL Injection (SQLi)',
      difficulty: 'hard',
      summary: 'Allows an attacker to interfere with database queries by injecting arbitrary SQL fragments into application inputs. Can result in full database exfiltration, authentication bypass, data destruction, and in some database setups, remote OS command execution.',
      remediation: 'Use parameterized queries (prepared statements) or object-relational mapping (ORM) frameworks with strict type binding.',
      portswigger: 'https://portswigger.net/web-security/sql-injection',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/sql-injection',
      owasp: 'https://owasp.org/www-community/attacks/SQL_Injection',
      youtube: [{ title: 'SQL Injection Masterclass', url: 'https://www.youtube.com/results?search_query=SQL+injection+bug+bounty+2024' }],
    },
    {
      id: 'ssrf',
      label: 'Server-Side Request Forgery (SSRF)',
      difficulty: 'hard',
      summary: 'Enables an attacker to coerce the backend web server into making HTTP requests to unexpected destinations. Commonly abused to read cloud metadata (AWS 169.254.169.254, GCP metadata), query internal microservices, or pivot behind the corporate firewall.',
      remediation: 'Enforce strict IP allowlisting for outgoing requests, disallow private IP ranges (RFC 1918), and disable HTTP redirection following.',
      portswigger: 'https://portswigger.net/web-security/ssrf',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/ssrf-server-side-request-forgery',
      owasp: 'https://owasp.org/www-community/attacks/Server_Side_Request_Forgery',
      youtube: [{ title: 'SSRF Exploitation & Cloud Metadata', url: 'https://www.youtube.com/results?search_query=SSRF+bug+bounty+2024' }],
    },
    {
      id: 'idor',
      label: 'Insecure Direct Object Reference (IDOR)',
      difficulty: 'medium',
      summary: 'Arises when an application exposes a reference to an internal implementation object (such as an account number or file path) in URL or API parameters without verifying user authorization. Attackers modify the ID to view or manipulate data belonging to other users.',
      remediation: 'Enforce rigorous server-side authorization checks on every state-changing request and consider using non-sequential UUIDs.',
      portswigger: 'https://portswigger.net/web-security/access-control/idor',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/idor',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/05-Authorization_Testing/04-Testing_for_Insecure_Direct_Object_References',
      youtube: [{ title: 'Finding IDORs in Bug Bounty Programs', url: 'https://www.youtube.com/results?search_query=IDOR+bug+bounty+2024+tutorial' }],
    },
    {
      id: 'csrf',
      label: 'Cross-Site Request Forgery (CSRF)',
      difficulty: 'medium',
      summary: 'Forces an authenticated end user to execute unwanted actions on a web application in which they are currently logged in. An attacker crafts a malicious link or script that tricks the browser into submitting unauthorized transactions on the victim’s behalf.',
      remediation: 'Implement anti-CSRF tokens (synchronizer token pattern) or ensure sensitive cookies are marked with SameSite=Lax or SameSite=Strict.',
      portswigger: 'https://portswigger.net/web-security/csrf',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/csrf-cross-site-request-forgery',
      owasp: 'https://owasp.org/www-community/attacks/csrf',
      youtube: [{ title: 'CSRF Attacks & Modern Protections', url: 'https://www.youtube.com/results?search_query=CSRF+bug+bounty' }],
    },
    {
      id: 'takeover',
      label: 'Subdomain Takeover',
      difficulty: 'hard',
      summary: 'Occurs when a DNS record (typically a CNAME) points to an external cloud or SaaS service (e.g., GitHub Pages, AWS S3, Heroku) that has been deleted or unclaimed. An attacker claims the remote resource and serves arbitrary malicious content on the company domain.',
      remediation: 'Regularly audit DNS zones for dangling CNAME records and remove DNS entries as soon as associated cloud assets are decommissioned.',
      portswigger: 'https://portswigger.net/web-security/host-header/exploiting',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/domain-subdomain-takeover',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/',
      youtube: [{ title: 'Subdomain Takeover Complete Guide', url: 'https://www.youtube.com/results?search_query=subdomain+takeover+bug+bounty+2024' }],
    },
    {
      id: 'cors',
      label: 'CORS Misconfiguration',
      difficulty: 'easy',
      summary: 'Improper Cross-Origin Resource Sharing configuration, such as dynamically echoing the Origin header with Access-Control-Allow-Credentials: true or using wildcard origins. Allows third-party websites to extract sensitive data and authenticated API responses.',
      remediation: 'Explicitly validate origin domains against a trusted whitelist and avoid configuring Access-Control-Allow-Origin: * alongside credentials.',
      portswigger: 'https://portswigger.net/web-security/cors',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/cors-bypass',
      owasp: 'https://owasp.org/www-community/attacks/CORS_OriginHeaderScrutiny',
      youtube: [{ title: 'CORS Misconfigurations in Bug Bounties', url: 'https://www.youtube.com/results?search_query=CORS+misconfiguration+bug+bounty' }],
    },
  ],

  // ── SAST ────────────────────────────────────────────────────────
  sast: [
    {
      id: 'hardcoded_secrets',
      label: 'Hardcoded Secrets & API Keys',
      difficulty: 'easy',
      summary: 'Authentication keys, private certificates, database credentials, or third-party service tokens embedded directly within source code repositories. Discovered using automated regex and entropy analysis tools like Gitleaks and Semgrep.',
      remediation: 'Store credentials in environment variables or managed secrets stores (AWS Secrets Manager, HashiCorp Vault) and enforce pre-commit git hooks.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/generic-methodologies-and-resources/external-recon-methodology#finding-api-keys-and-credentials',
      owasp: 'https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password',
      extraResource: { label: 'Gitleaks Documentation', url: 'https://github.com/gitleaks/gitleaks' },
      youtube: [{ title: 'Automated Secret Scanning with Gitleaks', url: 'https://www.youtube.com/results?search_query=gitleaks+secrets+scanning+tutorial' }],
    },
    {
      id: 'insecure_deserialization',
      label: 'Insecure Deserialization',
      difficulty: 'medium',
      summary: 'Untrusted user input passed directly to object deserializers (e.g., Python pickle, Java ObjectInputStream, PHP unserialize). Attackers manipulate serialized object state to trigger arbitrary method execution, achieve remote code execution, or tamper with application logic.',
      remediation: 'Use safe data interchange formats such as JSON or Protocol Buffers, or implement digital signatures to verify serialized data integrity.',
      portswigger: 'https://portswigger.net/web-security/deserialization',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/deserialization',
      owasp: 'https://owasp.org/www-community/vulnerabilities/Deserialization_of_untrusted_data',
      youtube: [{ title: 'Insecure Deserialization to RCE', url: 'https://www.youtube.com/results?search_query=insecure+deserialization+vulnerability+tutorial' }],
    },
    {
      id: 'command_injection',
      label: 'Command Injection (OS Injection)',
      difficulty: 'hard',
      summary: 'Unsanitized user-supplied data passed directly to a system shell command execution API (e.g., Python subprocess, os.system, Node.js exec). Attackers inject command separators (; | &&) to execute arbitrary commands with the privileges of the web application.',
      remediation: 'Avoid invoking OS shells; use programming language APIs that pass arguments as distinct arrays without shell parsing.',
      portswigger: 'https://portswigger.net/web-security/os-command-injection',
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/command-injection',
      owasp: 'https://owasp.org/www-community/attacks/Command_Injection',
      youtube: [{ title: 'OS Command Injection Exploitation', url: 'https://www.youtube.com/results?search_query=command+injection+exploitation+tutorial' }],
    },
  ],

  // ── Network ─────────────────────────────────────────────────────
  network: [
    {
      id: 'open_ports',
      label: 'Unnecessary Exposed Network Ports',
      difficulty: 'easy',
      summary: 'Open network ports running internal or sensitive daemons (e.g., Redis, SMB, RDP, MySQL) without perimeter firewall filtering. Exposes internal services to internet-wide reconnaissance, brute-force attacks, and direct protocol exploitation.',
      remediation: 'Implement a default-deny ingress firewall policy (AWS Security Groups, UFW) and restrict administrative ports to VPN tunnels.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/generic-methodologies-and-resources/pentesting-network',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/01-Conduct_Search_Engine_Discovery_Reconnaissance_for_Information_Leakage',
      extraResource: { label: 'Nmap Official Reference', url: 'https://nmap.org/book/man.html' },
      youtube: [{ title: 'Network Port Scanning with Nmap', url: 'https://www.youtube.com/results?search_query=nmap+port+scanning+tutorial+2024' }],
    },
    {
      id: 'service_version_exposure',
      label: 'Outdated Service Version Exposure',
      difficulty: 'medium',
      summary: 'Network daemons revealing verbose version banners (e.g., OpenSSH 6.x, Apache 2.2). Outdated services often contain published CVEs and ready-to-use exploit scripts that attackers identify via automated fingerprinting tools.',
      remediation: 'Suppress verbose software banners, apply regular operating system security patches, and remove legacy services.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server',
      extraResource: { label: 'National Vulnerability Database', url: 'https://nvd.nist.gov/' },
      youtube: [{ title: 'Service Fingerprinting and Exploitation', url: 'https://www.youtube.com/results?search_query=nmap+service+version+detection' }],
    },
  ],

  // ── SSL/TLS ──────────────────────────────────────────────────────
  ssl: [
    {
      id: 'weak_ciphers',
      label: 'Weak SSL/TLS Cipher Suites',
      difficulty: 'easy',
      summary: 'Legacy cryptographic algorithms (such as RC4, 3DES, EXPORT, NULL, or CBC ciphers) negotiated during TLS handshakes. Allows passive or active adversaries to decrypt intercepted traffic or exploit cryptographic downgrade flaws.',
      remediation: 'Configure the web server to negotiate exclusively modern AEAD cipher suites (e.g., TLS_AES_128_GCM_SHA256, ECDHE-RSA-AES128-GCM-SHA256).',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-ssl',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography',
      extraResource: { label: 'Qualys SSL Labs Analyzer', url: 'https://www.ssllabs.com/ssltest/' },
      youtube: [{ title: 'SSL/TLS Cipher Suite Security Testing', url: 'https://www.youtube.com/results?search_query=ssl+tls+security+testing+tutorial' }],
    },
    {
      id: 'deprecated_protocols',
      label: 'Deprecated Protocol Support (TLS 1.0 / 1.1 / SSLv3)',
      difficulty: 'easy',
      summary: 'Legacy protocols suffering from fundamental design flaws vulnerable to attacks like POODLE, BEAST, and DROWN. Modern security standards mandate disabling SSLv2, SSLv3, TLS 1.0, and TLS 1.1.',
      remediation: 'Disable SSLv3, TLS 1.0, and TLS 1.1 in web server configurations; enforce TLS 1.2 as minimum and prioritize TLS 1.3.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-ssl',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_Transport_Layer_Security',
      extraResource: { label: 'Mozilla SSL Configuration Generator', url: 'https://ssl-config.mozilla.org/' },
      youtube: [{ title: 'Why TLS 1.0 and 1.1 Are Broken', url: 'https://www.youtube.com/results?search_query=TLS+vulnerabilities+POODLE+BEAST+explained' }],
    },
    {
      id: 'certificate_issues',
      label: 'SSL Certificate Validity & Trust Flaws',
      difficulty: 'medium',
      summary: 'Expired certificates, self-signed certificates, missing intermediate chain certificates, or hostname mismatches. Breaks encryption trust and enables Man-in-the-Middle (MitM) adversaries to intercept or alter web traffic.',
      remediation: 'Deploy automated certificate management via ACME (Let’s Encrypt) and monitor certificate expiration with automated alerts.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-ssl',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels',
      extraResource: { label: "Let's Encrypt Free Automation", url: 'https://letsencrypt.org/' },
      youtube: [{ title: 'Understanding SSL Certificate Chains & MitM', url: 'https://www.youtube.com/results?search_query=ssl+certificate+security+issues' }],
    },
    {
      id: 'heartbleed_robot',
      label: 'Critical TLS Implementation Flaws (Heartbleed / ROBOT)',
      difficulty: 'hard',
      summary: 'High-severity structural vulnerabilities in specific TLS library implementations. Heartbleed (CVE-2014-0160) leaks process memory including private keys; ROBOT enables RSA decryption via Bleichenbacher padding oracle attacks.',
      remediation: 'Patch OpenSSL and web server binaries immediately to current vendor-supported versions.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-ssl#heartbleed',
      owasp: 'https://owasp.org/www-community/vulnerabilities/Heartbleed_Bug',
      extraResource: { label: 'Heartbleed Vulnerability Report', url: 'https://heartbleed.com/' },
      youtube: [{ title: 'Heartbleed and ROBOT Attacks Illustrated', url: 'https://www.youtube.com/results?search_query=heartbleed+vulnerability+explained' }],
    },
  ],

  // ── Dependencies ─────────────────────────────────────────────────
  deps: [
    {
      id: 'known_cve_deps',
      label: 'Known CVEs in Open Source Dependencies',
      difficulty: 'easy',
      summary: 'Utilizing third-party libraries and packages that contain publicly disclosed security vulnerabilities cataloged in the National Vulnerability Database. For example, remote code execution in Log4j (Log4Shell) or Apache Struts.',
      remediation: 'Incorporate automated software composition analysis (SCA) into CI/CD pipelines and configure automated dependency update bots (Dependabot).',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/generic-methodologies-and-resources/external-recon-methodology#finding-vulnerabilities-in-dependencies',
      owasp: 'https://owasp.org/www-project-dependency-check/',
      extraResource: { label: 'Open Source Vulnerability (OSV) DB', url: 'https://osv.dev/' },
      youtube: [{ title: 'Software Supply Chain Vulnerabilities: Log4Shell', url: 'https://www.youtube.com/results?search_query=dependency+vulnerabilities+log4shell+tutorial' }],
    },
    {
      id: 'transitive_deps',
      label: 'Vulnerable Transitive (Indirect) Dependencies',
      difficulty: 'medium',
      summary: 'Security defects introduced not by direct dependencies, but by sub-dependencies deep within the dependency graph. Often overlooked by developers because the vulnerable package does not appear directly in requirements.txt or package.json.',
      remediation: 'Run package lock file audits (npm audit, pip-audit) and pin or override vulnerable nested dependencies.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/generic-methodologies-and-resources/external-recon-methodology',
      owasp: 'https://owasp.org/www-community/Component_Analysis',
      extraResource: { label: 'npm Audit Security Guide', url: 'https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities' },
      youtube: [{ title: 'Securing Nested & Transitive Dependencies', url: 'https://www.youtube.com/results?search_query=transitive+dependency+vulnerability+security' }],
    },
  ],

  // ── Server Config ────────────────────────────────────────────────
  server: [
    {
      id: 'missing_headers',
      label: 'Missing HTTP Security Headers',
      difficulty: 'easy',
      summary: 'Absence of protective HTTP response headers such as Content-Security-Policy (CSP), X-Frame-Options, Strict-Transport-Security (HSTS), and X-Content-Type-Options. Leaves the application vulnerable to Clickjacking, MIME-sniffing, and downgrade attacks.',
      remediation: 'Configure the web server or reverse proxy to inject standard security headers on all HTTP responses.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/web-vulns-list#security-headers',
      owasp: 'https://owasp.org/www-project-secure-headers/',
      extraResource: { label: 'SecurityHeaders.com Analysis', url: 'https://securityheaders.com/' },
      youtube: [{ title: 'Essential HTTP Security Headers Explained', url: 'https://www.youtube.com/results?search_query=http+security+headers+guide' }],
    },
    {
      id: 'directory_listing',
      label: 'Enabled Directory Listing / Directory Browsing',
      difficulty: 'easy',
      summary: 'The web server generates an index listing of directory contents when an index file is absent. Leaks sensitive configuration files, source code archives, database backups (.sql, .bak, .zip), and internal documentation.',
      remediation: 'Disable directory browsing directives in web server configuration (Options -Indexes in Apache, autoindex off in Nginx).',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/web-server-exploits-by-method',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/09-Test_File_Permission',
      extraResource: { label: 'Apache DirectoryIndex Guide', url: 'https://httpd.apache.org/docs/2.4/mod/mod_dir.html' },
      youtube: [{ title: 'Information Disclosure via Directory Listing', url: 'https://www.youtube.com/results?search_query=directory+listing+vulnerability+apache+nginx' }],
    },
    {
      id: 'default_credentials',
      label: 'Default Administrative Credentials',
      difficulty: 'medium',
      summary: 'Administrative interfaces, database panels, or embedded services left configured with vendor default usernames and passwords (e.g., admin:admin, root:root). Routinely harvested by automated scanning bots and credential stuffing campaigns.',
      remediation: 'Mandate credential rotation upon initial setup, disable default accounts, and enforce multi-factor authentication (MFA).',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/pentesting-web/default-credentials',
      owasp: 'https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password',
      extraResource: { label: 'Default Credentials Database', url: 'https://github.com/ihebski/DefaultCreds-cheat-sheet' },
      youtube: [{ title: 'Credential Stuffing & Default Password Exploitation', url: 'https://www.youtube.com/results?search_query=default+credentials+penetration+testing' }],
    },
  ],

  // ── Server External ──────────────────────────────────────────────
  server_ext: [
    {
      id: 'dangerous_http_methods',
      label: 'Dangerous HTTP Methods Enabled (TRACE / OPTIONS / PUT / DELETE)',
      difficulty: 'easy',
      summary: 'Web server responds to potentially hazardous HTTP request methods. TRACE enables Cross-Site Tracing (XST) attacks that allow attackers to bypass HTTPOnly cookie protections, while improperly secured PUT or DELETE methods permit unauthorized modification or deletion of web resources.',
      remediation: 'Disable TRACE, TRACK, and arbitrary PUT/DELETE methods in web server configuration (TraceEnable Off in Apache; limit allowed methods to GET, POST, HEAD).',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/put-method-webdav',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods',
      extraResource: { label: 'OWASP HTTP Methods Testing', url: 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods' },
      youtube: [{ title: 'HTTP Verb Tampering & TRACE Method Attacks', url: 'https://www.youtube.com/results?search_query=http+methods+trace+options+put+pentesting' }],
    },
    {
      id: 'server_banner_disclosure',
      label: 'Verbose Web Server & Technology Banner Disclosure',
      difficulty: 'easy',
      summary: 'The HTTP Server and X-Powered-By response headers reveal exact software versions and underlying operating systems (e.g. Apache/2.4.41 Ubuntu, PHP/8.1.2). This eliminates attacker reconnaissance effort, enabling rapid targeting of unpatched known CVEs.',
      remediation: 'Configure ServerTokens Prod and ServerSignature Off in Apache, server_tokens off in Nginx, and strip X-Powered-By headers in application runtimes.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/web-server-exploits-by-method',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server',
      extraResource: { label: 'Apache ServerTokens Documentation', url: 'https://httpd.apache.org/docs/2.4/mod/core.html#servertokens' },
      youtube: [{ title: 'Web Server Fingerprinting & Banner Grabbing', url: 'https://www.youtube.com/results?search_query=server+banner+grabbing+information+disclosure' }],
    },
    {
      id: 'exposed_status_page',
      label: 'Exposed Server Status / Metric Monitoring Endpoints',
      difficulty: 'medium',
      summary: 'Diagnostic endpoints such as /server-status (mod_status), /server-info, /nginx_status, or Prometheus /metrics accessible without authentication. Discloses current client IP addresses, requested internal URLs, host resource utilization, and system worker states.',
      remediation: 'Restrict access to server status handlers exclusively to localhost (127.0.0.1 / ::1) or enforce strict IP whitelisting and mutual authentication.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/apache#server-status',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/05-Review_Webpage_Content_for_Information_Leakage',
      extraResource: { label: 'Apache mod_status Security Guide', url: 'https://httpd.apache.org/docs/2.4/mod/mod_status.html' },
      youtube: [{ title: 'Exploiting Apache Server-Status Information Disclosure', url: 'https://www.youtube.com/results?search_query=apache+server-status+exploit' }],
    },
    {
      id: 'slowloris_dos',
      label: 'Slowloris Partial HTTP Request Denial of Service',
      difficulty: 'hard',
      summary: 'Web server vulnerable to connection exhaustion when an attacker opens multiple slow connections and periodically sends fragmented HTTP headers to prevent timeouts. This exhausts concurrent connection worker threads with minimal attacker bandwidth.',
      remediation: 'Deploy reverse proxies (e.g. Nginx, Cloudflare) that buffer request headers before forwarding, or configure mod_reqtimeout in Apache with aggressive header completion limits.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/generic-methodologies-and-resources/pentesting-dos#slowloris',
      owasp: 'https://owasp.org/www-community/attacks/Slowloris',
      extraResource: { label: 'Cloudflare Slowloris Mitigation', url: 'https://www.cloudflare.com/learning/ddos/ddos-attack-tools/slowloris/' },
      youtube: [{ title: 'Slowloris Attack Mechanism & Countermeasures', url: 'https://www.youtube.com/results?search_query=slowloris+dos+attack+tutorial' }],
    },
  ],

  // ── Docker ───────────────────────────────────────────────────────
  docker: [
    {
      id: 'exposed_docker_api',
      label: 'Unauthenticated Exposed Docker Socket / API',
      difficulty: 'medium',
      summary: 'Docker daemon listening on TCP port 2375/2376 without TLS authentication. Any network-adjacent client can issue Docker API commands to spawn containers, mount the host filesystem, and achieve instant root access on the host.',
      remediation: 'Never expose Docker daemon sockets over the network without mutual TLS authentication; use local UNIX sockets with strict permissions.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/2375-pentesting-docker',
      owasp: 'https://owasp.org/www-project-docker-security/',
      extraResource: { label: 'Docker Daemon Security Best Practices', url: 'https://docs.docker.com/engine/security/' },
      youtube: [{ title: 'Hacking Exposed Docker APIs', url: 'https://www.youtube.com/results?search_query=docker+security+pentesting+2024' }],
    },
    {
      id: 'privileged_containers',
      label: 'Privileged Containers & Dangerous Host Mounts',
      difficulty: 'hard',
      summary: 'Running containers with the --privileged flag or mounting sensitive host filesystems (such as /var/run/docker.sock or root /). Disables container isolation safeguards and allows attackers to escape the container to the host kernel.',
      remediation: 'Run containers as non-root, avoid --privileged flags, and adopt security profiles such as AppArmor, SELinux, and seccomp.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/linux-hardening/privilege-escalation/docker-security/docker-breakout-privilege-escalation',
      owasp: 'https://owasp.org/www-project-docker-security/',
      extraResource: { label: 'Docker Bench for Security Tool', url: 'https://github.com/docker/docker-bench-security' },
      youtube: [{ title: 'Container Escape Techniques & Privileged Containers', url: 'https://www.youtube.com/results?search_query=docker+container+escape+privileged' }],
    },
  ],

  // ── DNS/Email ────────────────────────────────────────────────────
  dns: [
    {
      id: 'missing_spf_dkim_dmarc',
      label: 'Missing or Permissive SPF / DKIM / DMARC Records',
      difficulty: 'easy',
      summary: 'Lack of email validation DNS records allows malicious actors to forge emails that appear to originate from your legitimate company domain. Heavily exploited in business email compromise (BEC) and phishing campaigns against customers.',
      remediation: 'Publish strict SPF DNS records (v=spf1 ... -all), implement DKIM cryptographic signing, and configure DMARC with p=reject policy.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-smtp/dmarc',
      owasp: 'https://owasp.org/www-project-devsecops-guideline/latest/02e-Email-Security',
      extraResource: { label: 'MXToolbox Email Security Suite', url: 'https://mxtoolbox.com/spf.aspx' },
      youtube: [{ title: 'SPF, DKIM, DMARC Setup & Security Deep Dive', url: 'https://www.youtube.com/results?search_query=SPF+DKIM+DMARC+email+security+explained' }],
    },
    {
      id: 'dns_zone_transfer',
      label: 'Unrestricted DNS Zone Transfer (AXFR Enabled)',
      difficulty: 'medium',
      summary: 'Authoritative nameservers configured to allow arbitrary zone transfers (AXFR) to any requester. Reveals the entire DNS zone file, including staging subdomains, internal IP addresses, mail servers, and hidden hostnames.',
      remediation: 'Restrict DNS zone transfers to explicit IP addresses of secondary nameservers and disallow public AXFR queries.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-dns#zone-transfer',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server',
      extraResource: { label: 'DNS AXFR Command Reference', url: 'https://linux.die.net/man/1/dig' },
      youtube: [{ title: 'DNS Zone Transfer Attack & Reconnaissance', url: 'https://www.youtube.com/results?search_query=DNS+zone+transfer+attack+tutorial' }],
    },
  ],

  // ── WordPress ────────────────────────────────────────────────────
  wordpress: [
    {
      id: 'outdated_plugins',
      label: 'Vulnerable Outdated WordPress Plugins & Themes',
      difficulty: 'easy',
      summary: 'Third-party WordPress plugins and themes running outdated releases. Responsible for over 90% of WordPress compromises, commonly exposing unauthenticated file uploads, SQL injection, and administrative bypasses.',
      remediation: 'Enable automatic background updates, audit active plugins using WPScan, and remove inactive or unmaintained extensions.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/wordpress',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/',
      extraResource: { label: 'WPScan Vulnerability Database', url: 'https://wpscan.com/wordpress-security-scanner' },
      youtube: [{ title: 'WordPress Pentesting & WPScan Vulnerability Hunting', url: 'https://www.youtube.com/results?search_query=wordpress+pentesting+wpscan+tutorial' }],
    },
    {
      id: 'xmlrpc_exposure',
      label: 'Exposed WordPress XML-RPC Interface',
      difficulty: 'medium',
      summary: 'The xmlrpc.php endpoint enabled by default allows high-speed brute force attacks via the system.multicall method (testing hundreds of credentials in a single HTTP request) and acts as an amplification vector for DDoS attacks.',
      remediation: 'Disable xmlrpc.php via .htaccess or web server rewrite rules if legacy remote publishing apps are not actively required.',
      portswigger: null,
      hacktricks: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/wordpress#xmlrpc',
      owasp: 'https://owasp.org/www-project-web-security-testing-guide/',
      extraResource: { label: 'WordPress XML-RPC Hardening Guide', url: 'https://wordpress.org/documentation/article/xmlrpc-support/' },
      youtube: [{ title: 'XML-RPC Attack Vectors & Hardening', url: 'https://www.youtube.com/results?search_query=wordpress+xmlrpc+attack+tutorial' }],
    },
  ],
};

// Utility: sort vulns by difficulty within each scanner tab
export function getSortedVulns(scannerId) {
  const vulns = VULN_LIBRARY[scannerId] || [];
  return [...vulns].sort(
    (a, b) => (DIFFICULTY_ORDER[a.difficulty] || 2) - (DIFFICULTY_ORDER[b.difficulty] || 2)
  );
}

// Utility: search across ALL scanner tabs
export function searchAllVulns(query) {
  if (!query || !query.trim()) return [];
  const q = query.trim().toLowerCase();
  const results = [];
  for (const [scannerId, vulns] of Object.entries(VULN_LIBRARY)) {
    for (const v of vulns) {
      if (
        v.label.toLowerCase().includes(q) ||
        v.id.toLowerCase().includes(q) ||
        scannerId.toLowerCase().includes(q) ||
        (v.summary && v.summary.toLowerCase().includes(q)) ||
        (v.remediation && v.remediation.toLowerCase().includes(q))
      ) {
        results.push({ ...v, scannerId });
      }
    }
  }
  return results;
}

export const DIFFICULTY_META = {
  easy: {
    label: 'Easy',
    color: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    dot: 'bg-emerald-400 shadow-emerald-500/40',
  },
  medium: {
    label: 'Medium',
    color: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
    dot: 'bg-amber-400 shadow-amber-500/40',
  },
  hard: {
    label: 'Hard',
    color: 'bg-rose-500/10 text-rose-400 border-rose-500/30',
    dot: 'bg-rose-400 shadow-rose-500/40',
  },
};
